version: '3.8'
services:

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./node:/usr/src/app:ro
    depends_on:
      - app
  
  app:
    build: 
      context: ./node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"

  
  # db:
  #   image: mysql:5.7
  #   container_name: db
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=nodedb
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_USER=welles
  #   networks: 
  #     - node-network

# networks:
#   internal:
#     driver: bridge