version: '3'
services:
  app:
    build: 
      context: ./node
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    networks: 
      - node-network
    depends_on:
      - app
  
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=welles
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge