version: '3'
services:
  app:
    build: 
      context: ./node
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - internal
  
  # db:
  #   image: mysql:5.7
  #   container_name: db
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=nodedb
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_USER=welles
  #   networks: 
  #     - node-network

networks:
  internal:
    driver: bridge